version: '3.7'
services:
  app:
    container_name: rct-app-${CONTAINER_PREFIX}
    build:
      context: .

    # node_modules local
    # volumes:
    #  - '.:/app'
    #

    # node_modules inside the content
    volumes:
    - './src/:/app/src/'
    - './public/:/app/public/'

    ports:
      - ${APP_PORT}:3000
    environment:
      - NODE_ENV=development
